# Team Members:
# Lasya Reddy Mekala (G01473683)
# Supraja Naraharisetty(G01507868)
# Trinaya Kodavati (G01506073)
# Dhaanya S Garapati (G01512900)

name: survey-app
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: survey-backend
    restart: unless-stopped
    environment:
      
      DATABASE_URL: "mysql+pymysql://survey:surveypass@surveydb.cxic486y49se.us-west-2.rds.amazonaws.com:3306/surveydb"
      ALLOWED_ORIGINS: "http://localhost:8001"
    expose:
      - "8000"   

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: "/api"
    container_name: survey-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8001:80"   

